### ISSUE TITLE
Javascirpt error `Uncaught TypeError: undefined is not a function`

### ISSUE THREAD

**Issue by speedy111** [akeeba/fof#382]
Hello Nicholas,

I hate to say it, but with the latest changes, starting from https://github.com/akeeba/fof/commit/9f9b2920f694ab7962402ccc9bf54bdd6a1c9b87, I now get the Javascirpt error `Uncaught TypeError: undefined is not a function` (at least in Joomla 3).

Upon investigation it turned out that it's because the scripts are now loaded _before_ `bootstrap.min.js`. By doing so, scripts now can NOT use functions from `bootstrap.min.js`, such as e.g. `.tooltip()`.
With the current approach, this can only be solved by also loading `bootstrap.min.js` by Akeeba Strapper. Loading bootstrap twice might then also give additional conflicts. So this might not be possible to do this properly.

But then also this same issue holds for other scripts, such as `core.js`. So you also can't use those core Joomla Javascript functions, because they are not yet defined. Loading these scripts also twice is quite dirty, hard and not really doable.

I've read your note and I don't want to put oil on the fire, but I personally then prefer the previous method and don't support extensions which screw up Joomla. This also fixes the issues which I mentioned above.

Loading jQuery without getting issues from other extensions is quite a hell, isn't it...? :-(

**Comment by bhallaheemanshu** [comment]
http://geeksprogrammings.blogspot.com/2015/01/Uncaught-TypeError-undefined-is-not-a-function.html

   Fnally I found a solution to the error . this link provided me  explanation of why and what of this error and provided solution to it . Spent my 2 hours on this error

**Comment by nikosdion** [comment]
That's no new. Read what I wrote on July 4th, six months and three days ago: "You have two versions of jQuery, akeeba.jQuery (loaded at the top) and window.jQuery (loaded further down)." Which is exactly what the link you provided reads.
