### ISSUE TITLE
Language in filter behavior

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#413]
The filter model behavior should skip to filter the `language` field, or it will return only items with in the current language on multi-language website.

For example
``index.php?option=com_library&view=books&Itemid=108&lang=en``
Will return this query
```sql
SELECT `books`.*
FROM `#__library_books` AS `books`
WHERE (`books`.`language` LIKE '%en-GB%')
ORDER BY `books`.`library_book_id` ASC
```
It didn't even returned the `*`

And if we enabled the `language` model behavior:
```sql
SELECT `books`.*
FROM `#__library_books` AS `books`
WHERE (`books`.`language` LIKE '%en-GB%') AND `books`.`language` IN ('*','en-GB')
ORDER BY `books`.`library_book_id` ASC
```
Well~~

**Comment by Eighke** [comment]
Well I had some time today to finish that!

https://github.com/Eighke/fof/commit/7e8c711afc78f29badb930da4502d76dd5c2d636

I have implemented `blacklistFilters` but also `getBehaviorParam` and `setBehaviorParam`.
- `blacklistFilters` allow to blacklist some field from the filters behavior.
- `getBehaviorParam` and `setBehaviorParam` are dedicated method to set or get params to the behaviors. Allowing to pass information to the behavior (so, the behaviors can communicate with the model and with other behavior).

https://github.com/Eighke/fof/commit/485f5e22522832868ab8acf476802e29c06bae0a

Blacklist the language field if the language behavior is enabled.

Tell me if you have some review, change, anything else. Then I'll make the doc and PR.

**Comment by Eighke** [comment]
Ok I'll wait a little bit for FOF 3 to be more mature and I'll rewrite the code for it.

**Comment by nikosdion** [comment]
I have pulled in both behaviours in FOF 3. You can take a look whenever you want.

**Comment by Eighke** [comment]
Oki I will check that tomorrow. Thanks :)

**Comment by Eighke** [comment]
Well finally I finish it today. Already send the PR.

Btw, I was thinking about using the same system for emptynonzero?

**Comment by nikosdion** [comment]
Yes, please do. I don't like how emptynonzero is currently implemented. I like your method better :)

**Comment by Eighke** [comment]
A small change like that should be enough? : https://github.com/Eighke/fof/commit/40c84295b53dc8c601d141e65ac2adc684cf23ff

**Comment by nikosdion** [comment]
Yes!

**Comment by Eighke** [comment]
Done. :)
