### ISSUE TITLE
Issues with encryption

### ISSUE THREAD

**Issue by emilva** [akeeba/fof#421]
1) "AES"
In the Rijndael-128/192/256 cipher name, the numbers corresponds to the block size, and not the key size. AES is based on Rijndael-128, but with three different key lengths: 128, 192, and 256. You can adjust the strength by adjusting the key length. Case in point: MCRYPT_RIJNDAEL_192/256 is not AES.

2) Padding Oracle Attack
Padding Oracle attacks are possible since you are not using the encrypt-then-mac strategy to verify the integrity of the ciphertexts.

**Comment by nikosdion** [comment]
Closing after two and a half months of not providing any information which would provide any credibility to the issue.
