### ISSUE TITLE
error generating documentation

### ISSUE THREAD

**Issue by thinkerytim** [akeeba/fof#427]
When I run `phing doc-html` in the `fof/build` directory, I get the following error:

```julio@julio-VPCF11PFX ~/GIT_REPOS/fof/build $ phing doc-html
Buildfile: /home/julio/GIT_REPOS/fof/build/build.xml
 [property] Loading /home/julio/GIT_REPOS/fof/build/./build.properties
 [property] Unable to find property file: /home/julio/GIT_REPOS/fof/build/./build.properties... skipped```

Building the actual release using `phing git` seems to work fine however. Do I need to generate the `build.properties` file somewhere before trying to generate docs?

**Comment by nikosdion** [comment]
You can ignore the warning messages regarding build.properties. This is a file not shipped in any of our repositories as it contains keys to our server and S3.=

**Comment by thinkerytim** [comment]
Thanks Nik. Where should the output docs be located? In the `release` or the `documentation` directory?

**Comment by nikosdion** [comment]
In the release directory. That's our output directory when building just about anything.

**Comment by thinkerytim** [comment]
Thanks again for the quick assist.
