### ISSUE TITLE
Can't generate PDF on windows

### ISSUE THREAD

**Issue by compojoom** [akeeba/fof#434]
According to the docs I should be able to build the pdf docs on windows by using phing doc-pdf. Unfortunately it's not working for me:

>D:\Development\Joomla\akeeba\fof\build>phing doc-pdf
Buildfile: D:\Development\Joomla\akeeba\fof\build\build.xml
 [property] Loading D:\Development\Joomla\akeeba\fof\build\.\build.properties
 [property] Unable to find property file: D:\Development\Joomla\akeeba\fof\build
\.\build.properties... skipped

>FrameworkOnFramework > doc-pdf:

>     [exec] 'bin' is not recognized as an internal or external command,
>     [exec] operable program or batch file.

>BUILD FINISHED

>Total time: 0.2614 seconds

Any ideas?

**Comment by nikosdion** [comment]
Did you follow the README instructions to symlink to the buildtools repo?

**Comment by compojoom** [comment]
Yep, I did.
Also phing git works as expected - it generates the zip package. 

So, it's working for you on windows?

**Comment by compojoom** [comment]
Just tried the doc-epub. It generates a file, but I can't open it.  The epub ff addon tells me that container.xml is missing. And converting the file to pdf is also not working :(

**Comment by nikosdion** [comment]
I can't check on Windows. My sole Windows dev machine died two nights ago (fried motherboard) :(

**Comment by nikosdion** [comment]
FOF 3 will have its documentation in the GitHub wiki.
