### ISSUE TITLE
Associations

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#446]
Hi Nicholas,

I just finished to rewrite my associations field and behavior. It will be for FOF3, but I implemented it in FOF2 to check if it is working. You can check here.

Field: https://github.com/Eighke/fof/commit/ecdcc27899e7444036265d9a2c1e8fb9f67902b3
Behavior: https://github.com/Eighke/fof/commit/73464c4cb4259cc4db00a7f2d2b61277d574af40

It probably can be optimized, but it works well.

BTW, it will not work with J! 3.3.6, because of a bug in Joomla (https://github.com/joomla/joomla-cms/pull/6052). I'm not sure to copy/paste the `getAssociations` with the fix somewhere else in FOF, or just skip the version 3.3.6 (hoping they will merge the fix in J! 3.4~).

If it looks good for you I'll create the FOF3 field and behavior.

**Comment by nikosdion** [comment]
I'm afraid I can't accept that for inclusion in FOF. The Joomla! issue if fixed neither in Joomla! 3.3 not in 3.4. This means that it's not going to work in any supported Joomla! version without a core hack. I can't accept a feature which requires a core hack. Remember, in the past I declined implementing Tags support for the same reason.

**Comment by Eighke** [comment]
Yes I doubt it will be fixed in J! 3.4. But I didn't ask for a core hack. In my own version I have created a new helper (F0FLanguageAssociations :)). So we can do something similar or just implement the working `getAssociations` directly in the `associations` field.

And if one day in J! 4A they fix the bug we can reuse the JLanguageAssociations method (or not).

Well as you want. :)
