### ISSUE TITLE
Behavior params in fof.xml (and $config)

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#451]
Currently we can define only behaviors we want to use. But it is impossible to send some params on it.

It should be great if we could do that. A simple use should be to remove the `EmptyNonZero` behavior, and instead having a way to setup the `filterZero` param directly in fof.xml. It will allow to create flexible behaviors.

```xml
<behaviorParams>
    <param name="filterZero">1</param>
</behaviorParams>
````

No? :)

**Comment by nikosdion** [comment]
No. The fof.xml file should be used only as a set of training wheels, used for quick prototyping. That's why in FOF3 the default factory is BasicFactory (no fof.xml support except the Container, no lookup in frontend/backend and singular/plural views), not the MagicSwitchFactory (same behaviour as FOF2).

**Comment by Eighke** [comment]
Well the main goal was not really fof.xml itself but to add it on the `__contruct()`. Something like.

```php
if (isset($config['behaviourParams']) && is_array($config['behaviourParams']))
{
	foreach ($config['behaviourParams'] as $behaviourParams)
	{
		$this->setBehaviorParam($behaviourParams['name'], behaviourParams['value']);
	}
}
```

> no fof.xml support except the Container

What do you mean by "except the Container"?

**Comment by nikosdion** [comment]
The Container::getInstance always reads the fof.xml file. Otherwise the
Container would have to make assumptions about the namespaces used by your
code. The only way to let you tell the Container which namespaces to use
without having to hardcode them is through fof.xml.
