### ISSUE TITLE
Legacy paths for view

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#456]
You currently use some "legacy" paths for the view (/views), but it is not used in `Toolbar::getMyViews()`. Result a warning.
`JFolder: :folder: Path is not a folder. Path: /administrator/components/com_toto/View`

And of course no submenu. :)

**Comment by nikosdion** [comment]
What are you talking about? I am using the new directory /View (first letter uppercase, singular). The actual problem is that JFolder throws idiotic warnings instead of silently returning an empty array. Grrr....
