### ISSUE TITLE
Autoload is not working

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#457]
I think.

In Autoloader.php L.104
```php
$this->prefixLengths[$prefix[0]][$prefix] = $length;  print_r($this->prefixLengths);
```
Here `$prefix` is equal to `\Component\Admin` so `$prefix[0]` will be `\`. But on L. 227

```php
$first = $class[0];

if (isset($this->prefixLengths[$first]))
```
Here `$class` is equal to `Component\Admin` without the `\`. So $first will be `C`. So it will fallback on PSR-4 but $this->fallbackDirs is empty, so nothing will be loaded.

**Comment by nikosdion** [comment]
The leading backslash was added in old versions of PHP 5.3 and it was a bug. After PHP 5.3.4 (if I'm not mistaken) PHP stopped using the leading backslash when calling the autoloader.

BTW: The autoloader, as it says on the docblock, is copied from Composer. I'm pretty sure it does work :D

**Comment by Eighke** [comment]
Yes on the L.227 you haven't the \ because it is managed by PHP itself. But L.104 is not managed by PHP by what you send it.

And that we send is defined L301-302 in the Container.php

```php
$frontEndNamespace = '\\' . $this->componentNamespace . '\\Site\\';
$backEndNamespace = '\\' . $this->componentNamespace . '\\Admin\\';
```

So yes it cannot works. :)

**Comment by Eighke** [comment]
L.184-185 too. :)

**Comment by nikosdion** [comment]
Do you actually see it in practice not working or are you just guessing? As in, you have a component which doesn't work?

**Comment by Eighke** [comment]
I'm in a component which doesn't work. I'm converting my testing component step by step.

- Renamed views in View -> Ok
  - XML form -> Ok
  - PHP form -> Ok
- Renamed models in Model -> Fail
- Tested with Controller -> Fail

Even if I `die()` nothing happen, the file is just not loaded. For testing I changed the L. 184-185 to :
```php
$frontEndNamespace = $namespace . '\\Site\\';
$backEndNamespace = $namespace . '\\Admin\\';
```
And now my Model is loaded correctly.

Well now I'm testing the custom behaviours (inside Model/Behaviour) and it fail too.
