### ISSUE TITLE
Custom model behaviour

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#458]
Just a notice to remember. It should be added in the docs regarding the behaviour.

--------------
In FOF2 you can just copy / paste a behaviour because you have no autoload, so you will never touch to the code of the behaviour.

But in FOF3, if you are using custom behaviour (e.g. Model/Behaviour/Name.php) you will need to change the `namespace` every time to match your component namespace (e.g. `namespace Toto\Admin\Model\Behavior`).

Else the class_exists() will return false but will still load the file. And the second time class_exists() will be called you will got a cute Fatal error `Cannot redeclare class`.

**Comment by nikosdion** [comment]
Isn't that a reasonable and self-understood corollary of the class naming rules outlined in the documentation?

**Comment by Eighke** [comment]
If you never used namespace before it can be tricky. I searched 10 minutes before realizing it. I think someone who never used namespace could never find the problem.

BTW, you have a small mistake here in DataModel.php L2119-2120
```php
$this->container->getNamespacePrefix() . '\\Model\\Behaviour\\' . ucfirst($this->getName()),
$this->container->getNamespacePrefix() . '\\Model\\Behaviour',
```
$this->container->getNamespacePrefix() already got a backspace at the end, so you will got 2 and it break the Autoloading. I'll PR the fix.

**Comment by nikosdion** [comment]
Namespaces have been a PHP language feature for 5 years (since 5.3.0). Get on with the program :)

OK about the PR, I'll be waiting for it.

**Comment by Eighke** [comment]
Unfortunately many dev stick on PHP 5.3 because hoster stick on it... And you have a lot of frontend devs who have only basic knowledge in OOP.

But well, when I found the problem I was a little bit stupid... ^^'
