### ISSUE TITLE
Fix regarding the documentation

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#460]
> The first important thing to remember is that all directories containing classes are written with their first letter in uppercase and their name in singular. For example, it's Controller not controllers. This is a major and mandatory change over regular Joomla! naming conventions.

> The same applies for class files. The model is named Item.php, not items.php.

Haven't checked for Controller but for Model the name is plural. E.g Model/Articles.php. I don't know which one is the needed behavior.

> require_once JPATH_LIBRARIES . '/fof30/include.php' or die('FOF 3.0 is not installed');

Shouldn't we create a parent folder fof3 with all the version inside? Else the `/libraries` folder will be messy.

**Comment by nikosdion** [comment]
You can't create a parent folder for libraries. Joomla! limitation.

**Comment by Eighke** [comment]
Erf, ok. :/

Take a look the the plural name for model. One is wrong: the documentation or the current behaviour in FOF. :)

**Comment by nikosdion** [comment]
Fixed. Now it implements the intended behavior: it first looks for the exactly named Controller, Model and View (the same as the exact view name you're accessing) and if it's not found it will look for the canonical, singularized view name.
