### ISSUE TITLE
Model name problem with Camel or not

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#461]
Ok my case: I am trying to enable everything step by step. But I got a problem with the model name that sometime use Camel sometime use lower case.

E.g. if you are using fof.xml
```xml
<model name="contents">
</model>
<model name="Contents">
</model>
```

So for example Tags ($model->contentType to be correct) is using Camel. But relations use lowercase. So currently if you need both you have to use:

```xml
<model name="contents">
	<behaviors merge="1">Tags</behaviors>
	<relation name="types" type="belongsToMany"
		pivotTable="#__ngcontents_contents_types"
	/>
</model>
<model name="Contents">
	<config>
		<option name="contentType">com_ngcontents.content</option>
	</config>
</model>
```

**Comment by nikosdion** [comment]
Fixed with commit 2776522
