### ISSUE TITLE
Submenu not loaded

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#463]
The submenu are not loaded in the sidebar. After some search it come from the L.55-75 inside `View/DataView/Form.php`

The `$templateResult = $this->getRenderedForm();` where is the `\JHtmlSidebar::render()` is called before `$this->preRender();` where are added the submenus on the `JHtmlSidebar` (using renderLinkbarItems).

**Comment by nikosdion** [comment]
It should be fixed now.
