### ISSUE TITLE
Memory leak on N-N relation

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#464]
In a N-N relation, if we create the relation for the both model it will create a memory leak (I didn't tried 1-1 and 1-N relation yet).

```xml
<model name="Contents">
	<relation name="types" type="belongsToMany"
		pivotTable="#__ngcontents_contents_types"
	/>
</model>
<model name="Types">
	<relation name="contents" type="belongsToMany"
		pivotTable="#__ngcontents_contents_types"
	/>
</model>
```

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 6 bytes) in /Factory/BasicFactory.php on line 379`

**Comment by nikosdion** [comment]
No, I think the problem here is that you don't give it the field names for the two sides of the relation. When you try to instantiate the Contents model it sees the N:N relation. It wants to set it up but it doesn't know what is the remote side's key field. So it tries to instantiate the Types model. It has an N:N relation, so it wants to set it up but it doesn't know what is the remote side's key field. So it tries to instantiate the Contents model. Infinite loop, memory exhausted.

Use the remoteKey, pivotLocalKey and pivotForeignKey attributes to resolve the field names of the N:N relation and prevent FOF from trying to enter the infinite loop.

**Comment by Eighke** [comment]
Nope it doens't work. But what are used in the Model and what are checked in the Configuration looks different. In Configuration we are looking for localKey remoteKey ourPivotKey theirPivotKey pivotModel. Uhm. Well I tested the both, but the result is the same.

```xml
<model name="Contents">
	<relation name="types" type="belongsToMany"
		localKey="ngcontents_content_id" pivotLocalKey="ngcontents_content_id" pivotForeignKey="ngcontents_type_id" foreignKey="ngcontents_type_id"
		pivotTable="#__ngcontents_contents_types"
	/>
</model>
<model name="Types">
	<relation name="contents" type="belongsToMany"
		localKey="ngcontents_type_id" pivotLocalKey="ngcontents_type_id" pivotForeignKey="ngcontents_content_id" foreignKey="ngcontents_content_id"
		pivotTable="#__ngcontents_contents_types"
	/>
</model>
```
-------------
```xml
<model name="Contents">
	<relation name="types" type="belongsToMany"
		localKey="ngcontents_content_id" ourPivotKey="ngcontents_content_id" theirPivotKey="ngcontents_type_id" remoteKey="ngcontents_type_id"
		pivotTable="#__ngcontents_contents_types"
	/>
</model>
<model name="Types">
	<relation name="contents" type="belongsToMany"
		localKey="ngcontents_type_id" ourPivotKey="ngcontents_type_id" theirPivotKey="ngcontents_content_id" remoteKey="ngcontents_content_id"
		pivotTable="#__ngcontents_contents_types"
	/>
</model>

**Comment by Eighke** [comment]
Well the problem come from the Configuration. Tried to break the relation with a fake `pivotLocalKey` or `ourPivotKey` but nothing happen. :)

**Comment by nikosdion** [comment]
Try again after this commit

**Comment by Eighke** [comment]
Ok I'll try tomorrow. I'm out for today. :)

**Comment by Eighke** [comment]
Ok. So now if I change any attribute it crash except for the `foreignKey`. It is well sent to the BelongsToMany relation but even if I change it nothing happen.

But maybe it is because you don't use it?

I don't have memory break anymore but the datas send by the `Relation` are wrong. I'll send you a PR in the next 5 minutes. :)

**Comment by Eighke** [comment]
Ok, except the not used `foreignKey` everything good now.

**Comment by nikosdion** [comment]
I suppose with your PR it's all working now, right?

**Comment by Eighke** [comment]
Yep, I have just no idea why `foreignKey` is not used. For example the code below is working.

```xml
<model name="Contents">
	<relation name="types" type="belongsToMany"
		localKey="ngcontents_content_id" pivotLocalKey="ngcontents_content_id" pivotForeignKey="ngcontents_type_id" foreignKey="Nope"
		pivotTable="#__ngcontents_contents_types"
	/>
</model>
<model name="Types">
	<relation name="contents" type="belongsToMany"
		localKey="ngcontents_type_id" pivotLocalKey="ngcontents_type_id" pivotForeignKey="ngcontents_content_id" foreignKey="Nope"
		pivotTable="#__ngcontents_contents_types"
	/>
</model>
```

But I cannot remove it, if I delete the `foreignKey="Nope"`. I will got the memory leak again.

**Comment by nikosdion** [comment]
You are contradicting yourself. You say the foreignKey is not used but if you remove it you have a problem. The foreignKey *is* used, but you need to read the code to understand how.

**Comment by Eighke** [comment]
No no. I means: the value of `foreignKey` is not used in the code. The proof is the value I added here ( `foreignKey="Nope"`) is working without any problem (maybe you are using it somewhere else that I didn't check yet).

But the if you don't setup the `foreingKey` attribute, FOF will try to guess it. And here the memory leak come.
```php
if (empty($foreignKey))
{
	/** @var DataModel $foreignModel */
	$foreignModel = $this->getForeignModel();
	$foreignModel->setIgnoreRequest(true);

	$this->foreignKey = $foreignModel->getIdFieldName();
}
```
So yes like you said FOF will call the foreingModel which will call the foreingModel which... Infinite look. :)


BTW we got a new problem here:
```php
$relations    = $this->item->getRelations()->getData($relationName);
```
If you already added some relation in the pivot table for an item, it will work w/o any problem. But if you haven't added relation for an item, `$relations` will be all the rows of the relation table.

E.g: I have Contents and Types. In types I have 2 types (Article, Tutorial). If in my pivot table I have no relation for my current Content, it will return Article and Tutorial. But if I already linked only Article, it will be fine and only Article will be returned.

**Comment by nikosdion** [comment]
I will have to respectfully insist that you are wrong. See:

https://github.com/akeeba/fof/blob/fof3-wip/fof/Model/DataModel/Relation/BelongsToMany.php#L152 used in eager loading

https://github.com/akeeba/fof/blob/fof3-wip/fof/Model/DataModel/Relation/BelongsToMany.php#L234 and https://github.com/akeeba/fof/blob/fof3-wip/fof/Model/DataModel/Relation/BelongsToMany.php#L265 used to filter the foreign model when getting relationship data with getData (internally called when you fetch relations)

https://github.com/akeeba/fof/blob/fof3-wip/fof/Model/DataModel/Relation/BelongsToMany.php#L290 used in the relation filters behavior.

So I'm pretty sure the field IS used and you'll be sure as well if you study the code. And as I explained what you have is NOT a memory leak, it's an infinite loop inherent to the way many-to-many relationships work.

Since you're using the wrong foreign model column name I think it's pretty reasonable that the relationship doesn't work.

**Comment by Eighke** [comment]
> I will have to respectfully insist that you are wrong

I already say that I didn't check all your code. The parenthesis are important. =)
> (maybe you are using it somewhere else that I didn't check yet)

I was just a notice based on the test I have done on my component. I noticed that currently using a fake `foreingKey` will not break my relation for the action I have already checked. But my current test are limited to the basic (well basically using the Relation field in browse, read and edit view). That's all. :)

I think for the basic use you are using the foreingModel and in final we don't really care about the `foreingKey` (guessing :)).

Btw did you check for the other problem? Maybe I should open a new issue and close this one because they have no relation?

**Comment by nikosdion** [comment]
I wrote what I wrote trying to explain both things you mentioned. Have you tried using the *correct* foreignKey with your relation?

**Comment by Eighke** [comment]
Of course... I never used that except for test (so basically around 40 seconds, time to refresh my page and copy paste here ;)).

**Comment by nikosdion** [comment]
Maybe I didn't ask this correctly. Have you used the *correct* foreignKey when testing whether the second issue occurs or not? Because with a fake field it will certainly occur.

**Comment by Eighke** [comment]
No no it is my answer that can be misinterpreted. Bis:

Of course... I only used the fake `foreignKey` 40 seconds to check the problem and report it here. :)
