### ISSUE TITLE
buildQuery method doesn't use $model but $query  

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#469]
#468

Nope, it is not fine. ^^'

The return of `buildQuery` is $query. And $query is used directly inside `getItemsArray()`. None of this 2 methods are using $model or $this (except to trigger the hook and behavior). It is pure $db query. So if you use $model->whereRaw() nothing will happen.

Currently the Language and Enabled behavior are not working at all. But after this change they are working fine. You can check `Filter` that is working w/o any problem: it is using $query and not $model.

**Comment by nikosdion** [comment]
The only real problem is that I should have used onBeforeBuildQuery

**Comment by Eighke** [comment]
Shouldn't we use this method for `Own` too?

**Comment by nikosdion** [comment]
We could, but it's already working (by modifying $query in onAfterBuildQuery). If it ain't broken don't fix it.

**Comment by Eighke** [comment]
Roger. Tested your fix and it is working.
