### ISSUE TITLE
Render: header and field on empty (on browse form)

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#474]
Nicholas,

Currently for the Header if we return an empty value it will remove the `<th>`. This behavior is used for the "Filter only" but it can also be very good to remove a column based on some test. For example: showing the column only if you are administrator.

But for that we need Field to have a similar behavior. So, couldn't we do something similar on the Field?

It can be an attribute ($this->showField?) or just checking if `getRepeatable()` return NULL (we cannot filter on empty because we can have empty value) or a specific method?

```php
if ($field->isDisplayable)
{
	$field->rowid	 = $i;
	$field->item	 = $item;
	$labelClass = $field->labelClass ? $field->labelClass : $field->labelclass; // J! > 3.2.0 use labelclass;
	$class			 = $labelClass ? 'class ="' . $labelClass . '"' : '';
	$html .= "\t\t\t\t\t<td $class>" . $field->getRepeatable() . '</td>' . "\n";
}
```

**Comment by Eighke** [comment]
BTW:
```php
 $labelClass = $field->labelClass ? $field->labelClass : $field->labelclass; // J! > 3.2.0 use labelclass;
```
I checked and we need this line only for J! 3.2.0, we should remove it no?

**Comment by nikosdion** [comment]
> For example: showing the column only if you are administrator.

No. This is not what XML forms are supposed to be used for. You should use PHP or Blade templates. OR, if you want to go there, you can modify the XML form from you View before rendering it. But, seriously, this *IS DEFINITELY NOT* what XML forms are supposed to be used for.

> So, couldn't we do something similar on the Field?

No. This is not what XML forms are supposed to be used for.

> I checked and we need this line only for J! 3.2.0, we should remove it no?

Yes.

**Comment by Eighke** [comment]
Oki, I found a way using Joomla. You can just make the check in the setup and return false. :)
