### ISSUE TITLE
MagicSwitch doesn't work as excepted

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#476]
When I say as expected I mean: Like FOF2.

In FOF2 you could add behaviours or fields only in the backend and call them from the frontend, without creating any model.

But here it is not possible. If I create a Behavior or Field on the backend w/o creating the Model, it will fail if I call it from the frontend.

It is not a big deal for the `Field` because the frontend views are generally in PHP. But it is little bit less convenient for the `Behaviour`. You will have to create an empty Model in the backend to make it works.

No idea if you want to keep this behavior, if yes we should add some warning in the Wiki.

**Comment by nikosdion** [comment]
Or you could create a Behavior in the frontend which inherits the backend Behavior. The trick is *namespaces*.

**Comment by Eighke** [comment]
Yep right. If you have many Behaviors, the empty Model can be faster (well we are speaking about 1-2 minutes~~). :)

But in final you cannot use MagicSwitch if you are using a Behavior, Field or Helper (View.php L.1120). Except using your own libraries and adding it to the Autoloader. :)

**Comment by nikosdion** [comment]
The reason we're using the same namespace as the current model in use is because I want you to be able to override model behaviours only in the front-end / only in the back-end. This was impossible in FOF2.

**Comment by Eighke** [comment]
Yep yep I know, I just wanted to remember to add a small notice in the wiki. It is done now. :)
