### ISSUE TITLE
Problem in template order

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#478]
We have a problem in Single view. I'm calling `index.php?option=com_toto&view=content`. But it is not loading `/Content/item.php` but `/Contents/default.php` after a small check the order used in `View::loadTemplate()` is not the good one.

```
Array
(
    [0] => any:com_toto/Contents/item
    [2] => any:com_toto/Contents/default
    [4] => any:com_toto/Content/item
    [5] => any:com_toto/Content/default
)
```
The problem is that `/Contents/default.php` is the main template for Browse. So it will probably always be loaded instead of  `/Content/item.php`

After checking it is because we are sending `$this->getName()` (which is plural) to `ViewTemplateFinder::getViewTemplateUris`, so the plural path will always be load first, then the single path.

**Comment by nikosdion** [comment]
Do not use singular view directories UNLESS you have a concrete singular named view class. Since you're using the magic factories you MUST use the plural view directories for all your view template files.

This is NOT a bug and will NOT change. The behavior of FOF 2 was problematic, leading to the wrong view template routinely being loaded, therefore it was changed. If you think really hard –like I did– you will see that I am right.

**Comment by Eighke** [comment]
I didn't think about that. Right.

But in this case shouldn't the single view be used by default? If we refer to #460 the default View for the class will be the single one. But the default View for template is the plural one. So the current tree is:

View/Item/Html.php
View/Items/tmpl/default.php
View/Items/tmpl/item.php

So we will have `Items` only to manage the template and `Item` to manage the class. :/

**Comment by nikosdion** [comment]
Let me see if we're on the same page here.

If you're using concrete classes with any factory: FOF will use getName() to get the name of the View class to determine the view template directory. This means that it will use whatever name is assigned to the class.

If you're using the Magic or MagicSwitch factory WITHOUT concrete classes: FOF will use getName() to get the name of the View class to determine the view template directory. If it's a browse task it will be the plural name, if it's an add/read/edit task it will be the singular name.

So: if you use the magic factories you should ONLY use ONE view template directory, the singular one. If you use concrete classes, you should also use ONE view template directory (the singular one) _unless_ you break the conventions and use two separate concrete View classes, one for singular and one for plural views. So if you follow the conventions you don't need to have both Items and Item directories, you only need Item.

**Comment by Eighke** [comment]
We was not, thanks for the explanation. :)

I think I was confused by your recommandation to not used singural view:
> Do not use singular view directories UNLESS you have a concrete singular named view class. 

Everything in FOF is now make to use Singular in priority if possible (before #460 plural was not even called). But for the template you recommended the inverse. It make my poor brain making some crazy (stupid) translation (which was: you **cannot** use Singular view).

Well in final the recommandation should be more : use only Plural or only Sigular but not both if you haven't concrete classes.


We will need to make some warning in the Wiki, because it is not the FOF2 behavior  nor J! behavior. I am sure people will do exactly the same thing and will complain. :)

I added in it in my TODO list.

**Comment by nikosdion** [comment]
Please take a look at the fof3-wip branch of com_todo. I have completed the component today and could not reproduce this issue. Maybe we are still on a different page, but the code will help you understand what I’m saying. Take a look at the component’s frontend.
