### ISSUE TITLE
DefaultDispatcher

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#484]
The `DispatcherMagic` check for `DefaultDispatcher` from the component namespace.

My question is: for which use? We normaly have only one `Dispatcher` and if we come inside the `DispatcherMagic` that means we have no `Dispatcher`. I don't see any case where we will need a `DefaultDispatcher` instead of a `Dispatcher`?

No? Same question for the TA. :)

**Comment by nikosdion** [comment]
You *could* have multiple dispatchers. Imagine having a default dispatcher with common logic, a special dispatcher for CLI, another dispatcher for a JApplicationWeb bespoke application and skip the regular dispatcher for use with the Joomla! front-end (therefore requiring Magic). Remember, the dispatcher to be used is selected in the Container's parameters. When you create a new Container instance your options will override the fof.xml configuration so yes, it's perfectly possible to have multiple dispatchers and TAs. It's just not very common :)

**Comment by Eighke** [comment]
Oh I didn't think about that. That right it is uncommon but possible. My bad. :)

Thanks. :)
