### ISSUE TITLE
Created behaviour

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#487]
Hi Nicholas,

`Created` behaviour looks wrong. Because currently the `check()` is called before, so it will fail if the `created_by` or `created_on` are NOT NULL (that is what they should be).

- Changing them to NULL looks tricky for the database scheme (both fields are mandatory and should be NOT NULL).
- Having to override the `check()` for a "default" behaviour looks strange.
- Using `onBeforeSave()` looks wrong.

Should we change the `check()` to skip those fields like in FOF2?

What do you think about that?

**Comment by nikosdion** [comment]
I implemented a better solution without hardcoding magic fields. That was the entire idea behind the Created and Modified behaviours.

**Comment by Eighke** [comment]
Approved. :)
