### ISSUE TITLE
Non data views

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#489]
Nicholas, could we had a attrib in the `<view> <config>` in `fof.xml` for non-data views?

Currently even if we are using `MagicFactory` we need to create both controller and model for non-data views event if we have only some HTML to show and nothing more.

**Comment by nikosdion** [comment]
You are really supposed to create an empty Controller and Model for non-data views. Putting that logic in fof.xml creates complexity (= bugs!) and degrades performance. For a rare case like this that's unacceptable.

Besides, if it's static HTML with no parameters why don't you use layouts? Either a layout in an existing (data) view or put each message as a different layout of the same non-data view. In the latter case you can assign any existing model to the Controller (it doesn't even matter which one!) and write a single default method which changes the layout depending on the task being executed, therefore not requiring you to specify the layout in the URL and making the URL more easily routable to SEF URLs.

**Comment by Eighke** [comment]
Yep, I wanted to use layouts for all my static HTML in a single view, but w/o creating an empty controller and model for that. :)

Using a existing data view look tricky no? It will load a lot of code for nothing.

For fof.xml, it is just a `if` to change the called `$className` in the Factory I don't think it will degrades the perfs. :)

**Comment by nikosdion** [comment]
Believe me when I say that going through fof.xml WILL cause problems.

**Comment by Eighke** [comment]
I will try. :)

But you didn't answer for the existing data view? Bad idea no?

**Comment by nikosdion** [comment]
Not necessarily. If you add a new task the model is instantiated but no data is loaded off the database.

**Comment by Eighke** [comment]
Oki thanks, could be a good solution depending of the situation.
