### ISSUE TITLE
Using own lib for model behaviours

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#490]
Currently in Form we can use Field and Header from another lib using type="Lib.Field"
Really useful, it allow to create our own lib and adding inside all our custom Field and Header.

Can we add in FOF the same thing for model behaviours?

Or something to add `$prefixes`? Maybe we can create something like `$this->container->getRegisteredPrefixes()` that will return an array of prefix? And a way to add new prefix inside?

Or at least a way to override `addBehaviour` to add `$prefix` w/o rewriting all the code. :(

**Comment by nikosdion** [comment]
```php
$observer = new \Your\Custom\Lib\Behaviour($this->behavioursDispatcher);
$this->behavioursDispatcher->attach($observer);
```

Or, if you're trying to be a smartass:

```php
foreach(['Alpha', 'Beta', 'Gamma'] as $behaviour)
{
  $this->behavioursDispatcher->attach(new \Your\Custom\Lib\$behaviour($this->behavioursDispatcher));
}
```

Hardly worth the several dozen lines of code to do that in the framework.

**Comment by Eighke** [comment]
Ah, I forgot to say: it is for when we are using `addBehaviour` so in the `MagicFactory`.

The goal is to do something similar to form:
```xml
<behaviour>Lib.Name,Own,Private</behaviour>
```

Like that you can easily include your own library and use it directly.

**Comment by nikosdion** [comment]
Sorry, no, this won't happen. You are free to create per-component model behaviours which extend your library ones and then use them in the fof.xml OR you can go through behavioursDispatcher in the constructor. You already have two fine solutions.

**Comment by Eighke** [comment]
Oki too bad. :(

But I'll choose the solution to override the `addBehaviour` in de DefaultDataModel. Probably not the best I know, but the more convenient.

Thank anyway.
