### ISSUE TITLE
F0FFormFieldModel (don't display url when no entry is found)

### ISSUE THREAD

**Issue by PAlexcom** [akeeba/fof#493]
_F0F version 2.4.2_

The form should not display the URL of a __NONE__ entry (when it fallbacks to the none text).
_I don't know if the url could be disabled, but looking throw the code and debugging I guess it is not possible._

![joomla dev administration addsports teams](https://cloud.githubusercontent.com/assets/1648497/7168447/d2c16ba0-e3bd-11e4-93a6-9df4deb8695b.png)
![screen shot 2015-04-15 at 22 21 52](https://cloud.githubusercontent.com/assets/1648497/7168452/d675711a-e3bd-11e4-8161-010d4eb4147e.png)
![screen shot 2015-04-15 at 22 22 19](https://cloud.githubusercontent.com/assets/1648497/7168457/d9d755bc-e3bd-11e4-96c6-9778db0b4c26.png)

**Comment by nikosdion** [comment]
Nope, not possible. You'd need to write your own field class for that.

**Comment by PAlexcom** [comment]
Yes, I ended up creating a new field class. But anyway, with the default behaviour it should not display a link with no sense if there is no entry.

**Comment by nikosdion** [comment]
It doesn't know that there's no entry. Also please do keep in mind that XML forms are meant for forms with trivial features. What you're asking (conditional link) is not a trivial feature. It at the threshold or requiring some rudimentary business logic. FOF 3's ViewTemplate <https://github.com/akeeba/fof/wiki/ViewTemplate-Field> field type is more apt to this task.
