### ISSUE TITLE
command "php ../buildfiles/tools/link.php `pwd` " error

### ISSUE THREAD

**Issue by charles-zh** [akeeba/fof#503]
I run "git clone xxxx" command and downloaded buildfiles & fof code files. But when I run the command in ubuntu 14.04:
php ../buildfiles/tools/link.php `pwd`

I got error:
Akeeba Build Tools - Linker
Internal file and directory symlinker
-------------------------------------------------------------------------------
Copyright ©2010-2015 Nicholas K. Dionysopoulos / AkeebaBackup.com
Distributed under the GNU General Public License v3 or later
-------------------------------------------------------------------------------
Hard linking files...
Symlinking files...
Symlinking folders...
FAILED SYMLINK : /home/wwwroot/src/fof/fof/build/bin
FAILED SYMLINK : /home/wwwroot/src/fof/fof/build/buildlang
FAILED UNLINK  : /home/wwwroot/src/fof/fof/build/phingext
FAILED SYMLINK : /home/wwwroot/src/fof/fof/build/tools

**Comment by nikosdion** [comment]
Please check your permissions. The script does work on Ubuntu 14.04. In fact, Ubuntu 14.04 is the second dev environment I'm testing with :)
