### ISSUE TITLE
Foiled by FOF

### ISSUE THREAD

**Issue by wilsonge** [akeeba/fof#509]
Hey Nic,
So despite the tag fixes earlier I'm still being foiled by FOF and would appreciate a thought. So basically my custom component I'm building at the moment is a weird one. I'm trying to retrieve articles against a given tag and category. The user needs to select a single tag in the backend and then we render the articles in the frontend based on the ID stored. So with that in mind I'm using the tag field and the multiple="false" attribute which means it's just rendering a select box - all good so far...

https://github.com/akeeba/fof/blob/development/fof/Form/Field/Tag.php#L117-L134

The issue is the code above. If you save a tag then this code actually overwrites my stored value. This feels like it should be a bug - but then again I'm not 100% sure on exactly what the code is there to do and if removing it has consequences?

Thanks for any thoughts you have in advance!

**Comment by Eighke** [comment]
If I remember in Joomla the tags are grabbed inside the `Model` using some helper method. In FOF the tags are grabbed directly in the `Tags` field. So if you are using the Joomla way to store the value, yes it will be overwritten in the field after.

Maybe we could remove those lines from here and do something inside the Tags behavior instead. But it will not solve your problem, because you need to enabled the Tags behavior and it will just overwrite your value in a different place.

**Comment by nikosdion** [comment]
If you want to select a single tag of items unrelated to the current item you must not use the Tag field. What you are looking for is a GenericList with a helper class and method to load the tags from Joomla's database.

**Comment by wilsonge** [comment]
JFormField Tag extends from JFormFieldList. If you don't force the value to be set in the getOptions method then it works perfectly. I'm not quite understanding why we are forcibly overriding the value being stored in the database. Could we not make it run only if no value could be found?

**Comment by nikosdion** [comment]
@Skullbock Do you remember why this field was implemented this way? I've never used it myself.

**Comment by Eighke** [comment]
@wilsonge No it will not work "automaticaly". If you don't force it you will need to get the current tags like in Joomla (inside the model). E.g. in the com_content:

```php
// admin/models/article.php L.286
$item->tags = new JHelperTags;
$item->tags->getTagIds($item->id, 'com_content.article');
```

So currently we are doing this part directly inside the `Tag` field. It probably should be inside the `Tags` behavior and not here.

But the `Tag` field is supposed to work only with Joomla Tag, so it should not be a problem even in the current implementation.

**Comment by nikosdion** [comment]
@Eighke Since you seem to be using the Tag behaviour and field would you like to refactor it? As I said, I'm not using the darn thing.

**Comment by Skullbock** [comment]
@nikosdion i remember it as because of UCM. We needed a content type in the UCM table to save tags. On the code side, we did it one night at jab14 i believe and since then i never used it in real world projects so it could definetly wrong as of now...

**Comment by nikosdion** [comment]
I guess we could move that code inside the Tags behavior, then?

**Comment by Skullbock** [comment]
Yes, it should live there. Again, not sure 100% since it was too much time ago. Maybe some more code comments there would've been helpful. My bad :)

**Comment by nikosdion** [comment]
As I say, you don't write the comments for yourself at the time you commit the code. You write the comments for yourself in 6+ months. 24 months later we see exactly why comments are a good idea and lack of comments, well, not so good :)

**Comment by Eighke** [comment]
@nikosdion Ok I will refactor it. I will wait to understand George problem to be sure we are speaking about the same think.

**Comment by nikosdion** [comment]
@Eighke OK! Thank you very much :)

**Comment by wilsonge** [comment]
So currently in the CMS you load the tags in https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_contact/models/contact.php#L334-L339. It would appear we are doing it in the form field. So if your tags come from another source (i.e. it's a specific set of tags then you are screwed). Just tested and just wrapping that block of code in
```php
		if (!$this->value)
		{
```

is enough. But I agree that moving the loading into the table behaviour would make more sense.

**Comment by Eighke** [comment]
@wilsonge I finished the refactor, you can take a look. I added those lines for you:

```php
if ($model->$tagField)
{
	return;
}
```

So if the tag field already has a value we will use it directly. :)
