### ISSUE TITLE
hasTags in Tags behavior

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#511]
Nicholas,

Another question, currently to use the Tags we need: to enabled the Tags behavior **and** to define `_has_tag`. In FOF2 it was normal because the tags behavior was added by default, and we needed to define with table will use it.

But now in FOF3, we have to enable this behavior manually. I don't think `_has_tag` and `hasTags` are needed anymore, at least in the behavior.

**Comment by nikosdion** [comment]
As I said in the other issue, I've not written the tags implementation and I've never used it. If you can produce a short example, e.g. one based on com_todo, I'd be happy to work with it and refactor the tags implementation. I currently don't have the time to start learning how tags work, write an example *and* refactor the code. Can you help me help you?

**Comment by Eighke** [comment]
Well it is working, it just not optimized for FOF3.  Basicaly we are doing that :

```php
// Inside fof.xml or in the __contruct
$hasTag        = 1;
$enabledTag = 1;

// In the model
if (enabledTag) {
    DoTags()
}

DoTags () {
    if ($hasTag) {
       //
   }
}
```

We are enabled 2 variables to 1 to do only 1 and unique action.

I'll check to add tag on the com_todo.

**Comment by nikosdion** [comment]
Thanks!

**Comment by Eighke** [comment]
Ok I just noticed that has_tag was already removed from fof.xml, but still inside the Tags behaviour. So I'll need to refactor the Tags behaviour first.

**Comment by nikosdion** [comment]
Great! Go ahead!

**Comment by Eighke** [comment]
I had many problem and was close to become crazy, but the refactor is done. You can merge it. :)
