### ISSUE TITLE
docs about fof.xml still correct?

### ISSUE THREAD

**Issue by compojoom** [akeeba/fof#515]
https://github.com/akeeba/fof/wiki/The-XML-configuration-file
The docs state that one could use this:

```xml
<!-- Dispatcher configuration -->
        <dispatcher>
            <option name="defaultView">items</option>
        </dispatcher>
```
I tried wit f0f3 and it didn't have any effect. What seems to work is creating my own Dispatcher class and overriding $defualtView in it. 

Is this section of the docs still correct for f0f3?

**Comment by nikosdion** [comment]
Currently out of country. Should work but ONLY if you do NOT have a custom class, like all objects in FOF 3. This is intentional for performance and sanity reasons.

**Comment by compojoom** [comment]
closing this for now.
