### ISSUE TITLE
Searchable field for several columns?

### ISSUE THREAD

**Issue by compojoom** [akeeba/fof#516]
I'm playing around with the .xml headers and what I'm wondering is if there is an option to create a single search field that would then search for a value in several columns?

Right now when I set a type="Searchable" to my headers FOF renders several search fields.

**Comment by nikosdion** [comment]
Automatically? No. You can create a search field with a name that does not correspond to an existing column in the database and then have your model apply it as a filter against multiple columns. But you do need to write specialized code in your Model for that to work, it is not automatic. Just like we do in Akeeba Subs in some views.

**Comment by compojoom** [comment]
Okay, easy enough! Done!

Thanks!
