### ISSUE TITLE
Model relations and forms?

### ISSUE THREAD

**Issue by compojoom** [akeeba/fof#517]
I have my own users table where I store address and other data about the user. 

My Users model has a hasOne relations to the joomla user's table.
```php
$this->hasOne('user', 'JoomlaUsers', 'user_id', 'id');
```
I've copied the code from akeebasubs so it's all fine :)

I have a Bookings model. The bookings model has this:
```php
$this->hasOne('user', 'Users', 'user_id', 'user_id');
```

Now I thought that if in my form.default.xml I do:
```xml
 <field name="user.user.name" type="Text" empty_replacement="–––"
	           show_link="true"
	           url="index.php?option=com_capartments&amp;view=User&amp;id=[ITEM:ID]"
		    />
```

This would actually take the name from #__users table. But it doesn't. 

So what I ended up doing is creating 2 hasOne relations:
```php
		$this->hasOne('user', 'Users', 'user_id', 'user_id');
		$this->hasOne('juser', 'JoomlaUsers', 'user_id', 'id');
```

Now if I do user.birthday - I would read my own table. and If I do juser.name -> it would read the data from the #__users table.
It works, but I would like to know if there is an easier way? 

Also what I'm wondering is - am I running into the eagerLoading problem in my backend views? Basically my view would display data from 3 tables. Is FOF loading each record at the time I need it and is there any way to it load all the data before hand, since I'm always going to need it?

**Comment by nikosdion** [comment]
> Now I thought that if in my form.default.xml I do:
> 
>  <field name="user.user.name" type="Text" empty_replacement="–––"
>                show_link="true"
>                url="index.php?option=com_capartments&amp;view=User&amp;id=[ITEM:ID]"
>             />

You can do that, as long as you set the attribute relation_depth="2" in your <form> tag, see https://github.com/akeeba/fof/wiki/XML-Forms <https://github.com/akeeba/fof/wiki/XML-Forms>

**Comment by compojoom** [comment]
FOF's sooo coool!
https://www.youtube.com/watch?v=AOzkN8dHnjk

Thanks!
