### ISSUE TITLE
Scaffolding?

### ISSUE THREAD

**Issue by compojoom** [akeeba/fof#519]
After few days of working with FOF I would that there is a scaffolding feature & it sounds amazing when prototyping. So I decided that I would test it for my new view since I hate copying the xml files from the other views.

In my component entry file capartments.php I have this:
```
FOF30\Container\Container::getInstance('com_capartments', array(
	'scaffolding' => true,
	'saveScaffolding' => true
))->dispatcher->dispatch();
```

I'm navigating to the Parkings view, that doesn't have a view yet, but all I get is:

> 500 Layout auto:com_capartments/Parkings/default not found. 

Is there anything specific I need to do in order for scaffolding to generate the form.default.xml and form.form.xml?

**Comment by nikosdion** [comment]
Yes, you need to use the MagicSwitchFactory factory as well. By default the BasicFactory is used which tries to find a concrete class and fails dead when one is not found. The MagicSwitch factory will try to magically provide suitable MVC classes. Scaffolding is just a switch to enable even more magic in the factory ;)

**Comment by compojoom** [comment]
No, that wasn't the issue. I was using the magicFactory and it is able to create the classes. The problem was in the fof.xml file. I've copied the container node from AS and it had scaffolding = 0

As soon as I removed that line from there the views were generated. 

Scaffolding is really awesome! I wish I knew about it few days ago :)

I think that we should link to the scaffolding section here: https://github.com/akeeba/fof/wiki/Getting-started-with-a-FOF-component

**Comment by nikosdion** [comment]
Scaffolding is how I created all the views in Akeeba Subs 5. It saved me 50% of the time I'd need to spend creating the form files :)

**Comment by compojoom** [comment]
Yea, yea! It's great! Just let us put it out the Getting started guide instead of having it listed somewhere down on the right :)

**Comment by nikosdion** [comment]
It's a documentation wiki, feel free to make this change :) Collaboration FTW!!!

**Comment by compojoom** [comment]
Done.

**Comment by nikosdion** [comment]
Thank you!
