### ISSUE TITLE
Non-data View with a form?

### ISSUE THREAD

**Issue by compojoom** [akeeba/fof#524]
I have a view that should display a form. 1 field with value from model 1 and another field with the value from Model 2. And there should be a Generate button. 

I've setup F0F to use a non-data view, but I just wondered - is there a way to actually still render a form without too much fuss?

**Comment by nikosdion** [comment]
If you are going to interpolate data from 2 or more models the non-fuss way is writing your own forms in PHP. Which is what you have already done, so... :)

**Comment by compojoom** [comment]
pfu, I had to do
```php
 $this->container->factory->model('Apartments')->getItemsArray()
```
and then build a whole select tag in html. This is already way too much work for the day :D

cheers!
