### ISSUE TITLE
Possible values for translate?

### ISSUE THREAD

**Issue by compojoom** [akeeba/fof#528]
Some fields have a translate parameter. For example Model, Checkbox, Relations. 
i've copied some code from Akeebasubs and there you use translate="false", however your check is

if($translate == true) 

since translate contains the string "false" it equals true. 

So my question here is - should we fix the code to accept both false, true as values or should we note in the documentation that correct values for translate are 0,1?

**Comment by nikosdion** [comment]
The correct values are 0 and 1. I think the forms with translate="false" came from bad copy paste from a previous version of the component.

**Comment by compojoom** [comment]
Good updated the wiki to reflect this.

**Comment by nikosdion** [comment]
Thank you!
