### ISSUE TITLE
Why is setState returning the state?

### ISSUE THREAD

**Issue by compojoom** [akeeba/fof#529]
Hey guys,
Is there a reason why the model setState actually returns the value set? 
When we use a magic property, then we don't return anything. 

The problem when we return value in setState is that we can't use chaining anymore. 
$model->setState('enabled', 1)->get() -> will fail
where
$model->enabled(1)->get() will succeed. 

I see that this is the same behavior in the legacy model in joomla, but the new base model actually no longer does this. Any thoughts?

**Comment by nikosdion** [comment]
Legacy code. No other reason.
