### ISSUE TITLE
Behavior vs Behaviour

### ISSUE THREAD

**Issue by compojoom** [akeeba/fof#542]
I see some places in the code where we use behavior and other places where we call it behaviour. 

The title of the wiki page is: https://github.com/akeeba/fof/wiki/Model-behaviors, but after that we all refer to it as Behaviours. 

I missed that part and was placing my behaviors filter in the behavior folder, wondering why it's not being picked up. 

In the dataModel we have behaviourDispatcher, but behaviorParams: setBehaviorParam, getBehaviorParam

Right now in the code we have 75 occurrences of Behavior and 135 of Behaviour. So when to use which?

**Comment by nikosdion** [comment]
Look at the folder structure of FOF itself

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.akeebabackup.com
Στις 11 Αυγ 2015 11:17 π.μ., ο χρήστης "Daniel Dimitrov" <
notifications@github.com> έγραψε:
