### ISSUE TITLE
Integer Field in Browse View

### ISSUE THREAD

**Issue by Skullbock** [akeeba/fof#543]
Hi nicholas, 
    i found a small issue with displaying an integer field in a browse view using a form.
Basically, it will just display an empty space instead of the integer value.

I traced it back to this line:

https://github.com/akeeba/fof/blob/development/fof/Form/Field/Integer.php#L131

I don't know why, but it gets treated as a list field, trying to show the active value between a series of options, but there is no options in a pure integer field.

Is this done on purpose?

**Comment by nikosdion** [comment]
Yes, it is on purpose. Check the JFormFieldInteger field we are extending from. It's supposed to create a drop-down list of values, so we have to go through options.

**Comment by Skullbock** [comment]
Yeah i noticed. But this gives the following issue: 
Since we're using scaffolding, and deciding the type of FOFField to use based on the table's columns type, every integer / decimal / float column gets rendered as null, because it expects it to be part of a list.

Thoughts?

**Comment by nikosdion** [comment]
Hm, do you think we could change the scaffolding to generate a text field with a formatting suitable for these numbers?

**Comment by Skullbock** [comment]
Could be, yes.
Or maybe have a dedicated form field for numbers?
I saw you're using something like that in akeeba. We could create a field with attributes like "decimals", "separators", etc to display numbers. Extending Text

**Comment by nikosdion** [comment]
I love the idea. Do it :)
