### ISSUE TITLE
Using Layouts in FOF

### ISSUE THREAD

**Issue by wilsonge** [akeeba/fof#548]
Since 3.2 in Joomla `JLayouts` have checked for component specific overrides https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/layout/file.php#L365-L382

Specifically in my case I'm looking to use a common modal contents in the frontend and backend of my component - as was aiming to use a JLayout for that

However in FOF we never check for any component specific overrides - only the other 3 (Joomla's layouts directory, template overrides and a custom path).

Whilst I can configure a custom path to point to a component folder I was wondering if there was a reason why we don't check for components or whether it was just because the FOF layouts support predated this feature in Joomla

**Comment by nikosdion** [comment]
No specific reason, just that we implemented this feature before Joomla! 3.2. Can you do a PR to add this feature?

**Comment by photodude** [comment]
Any thoughts on this feature being implemented?

**Comment by nikosdion** [comment]
You mean the JLayouts helper in Blade implemented in FOF 3 for over a year? Or the generic helper implemented since FOF 2 about 3 years ago? :D
