### ISSUE TITLE
Relations during onAfterSave

### ISSUE THREAD

**Issue by Skullbock** [akeeba/fof#552]
Hi @nikosdion , i was checking out the relations (in particular, the belongsTo in this case) in FOF3.
I have a particular case which is not behaving as expected, and wanted to know if it's by design or i'm doing something wrong.

I have this usecase:

1) **Orders** model with a hasMany('payments') relationship
2) **Payments** model with a belongsTo('order', 'Orders') relationship

now, when i do 

```php
<?php
$paymentModel->find(1)->order->toJson();
?>
```

it works as expected. 
But if i try:

```php
<?php
/**
 * Model for Payments
 */
class Payments extends DataModel
{
   .....
    /**
     * Whenever we save a payment, let's move the order status too
     */
    protected function onAfterSave() {
    	if ($this->order && $this->status != $this->order->status) {
    		$this->order->status = $this->status;
    		$this->order->save();
    	}
    }
}
?>
```

it doesn't work. From my research i got that is because the parentModel property in the relation class is not populated with the current item, but is still empty. 

Am i missing something?

**Comment by nikosdion** [comment]
If I understand you correctly: When you're saving relations you need to use push instead of save.

**Comment by Skullbock** [comment]
I'll try that, but what's happening there is that the order variable is not populated, so even doing order->status results in a "not defined property" warning

**Comment by nikosdion** [comment]
Are you loading before save? (I think you do) If so, the existing relation has been loaded. If you add a new relation (order) or modify/remove an existing one you need to use push() on the base model (payment) instead of save() on the relation (order).

Are you saving a new record from scratch? If so, there is no relation loaded. You will need to load the just-saved record to populate the relation. After doing whatever you want in the relations use push() to save them to the database.

Are you cloning an existing record? You need to reload the record after saving it since the primary key has changed. It's just like the previous case.

**Comment by Skullbock** [comment]
Sorry but it seems it doesn't work with push() either.
Here is the code

```php
<?php
/**
 * Controller class for Carts
 */
class Order extends DataController {

	public function pay() {

		$model = $this->getModel('Payments');

		// Load the id and slug. Either one defines which level we shall load
		$id = $model->getState('id', 0, 'int');

		// If we do not have a valid level ID throw a 404
		if (!$id) {
			throw new ItemNotFound($id, 404);
		}

		// Load the payment
		try {
		    $payment = $model->findOrFail($id);
		} catch (FOF30\Model\DataModel\Exception\RecordNotLoaded $e) {
		    throw new ItemNotFound($id, 404);
		}

		// Process response
		if ($paymentResponse->isSuccessful()) {
		    
		    $payment->status = 'success';
		    $payment->transaction_id = $paymentResponse->getTransactionReference();
		    $payment->save();

		}
	}
}

```

and then the model class:

```php

<?php
/**
 * Model for Payments
 */
class Payments extends DataModel
{
	public function __construct(Container $container, array $config = array())
    {
        parent::__construct($container, $config);

        $this->belongsTo('order', 'Orders', 'foo_order_id', 'foo_order_id');
    }

    /**
     * Whenever we save a payment, let's move the order status too
     */
    protected function onAfterSave() {
    	if ($this->status != $this->order->status) {
    		$this->order->status = $this->status;
    		$this->push();
    	}
    }
}
```

Results in 
Notice: trying to get property out of a non-object on $this->order->status

**Comment by Skullbock** [comment]
Ok, i confirm that you were right (as always).

"Are you saving a new record from scratch? If so, there is no relation loaded. You will need to load the just-saved record to populate the relation. After doing whatever you want in the relations use push() to save them to the database."

This was my case. Should this be included by default in the relation manager, so whenever a record is created, its relations are reloaded?

**Comment by nikosdion** [comment]
Hm, yes. That would be a good idea. Care to do a PR? Mind you, the reload should only run when the value of the key field changes after the save.

**Comment by Skullbock** [comment]
I'll try not messing it up :)

**Comment by nikosdion** [comment]
Don't worry, I'm here to do code auditing :p

**Comment by Skullbock** [comment]
https://github.com/akeeba/fof/pull/554

From my tests, a simple rebasing does the trick
