### ISSUE TITLE
Relations in JSON

### ISSUE THREAD

**Issue by Skullbock** [akeeba/fof#557]
Hi @nikosdion i have found a small issue in the DataViewJson class:

https://github.com/akeeba/fof/blob/development/fof/View/DataView/Json.php#L81

I noticed that you load the items by using getItemsArray() instead of get().
This skips any possible eagerloading set with "with" in the current model, therefore causing a bit of problems in the json lists with relations.

Should i PR a fix for this?

**Comment by nikosdion** [comment]
Yes, please. That's leftover code from FOF 2 I forgot to refactor...

**Comment by Skullbock** [comment]
See https://github.com/akeeba/fof/pull/558
