### ISSUE TITLE
Fields rowid

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#571]
I found a small problem, in the Fields $rowid is supposed to be "A monotonically increasing number", but currently it is the field's database id.

It has no impact on current Fields The problem is only if we want to implement some new Field and use it as it should be.

It is easily fixable, but I'm not sure if you want to keep the current behaviour instead?

**Comment by Eighke** [comment]
Oh, in final it is a real bug, it breaks the Ordering field when using the input instead of the drag & drop.

**Comment by nikosdion** [comment]
I just pushed a commit to fix it. Can you please verify?

**Comment by Eighke** [comment]
Nope it looks like the first row has to be 0, not 1. I fixed it + a small change in the toolbar.

**Comment by nikosdion** [comment]
Thank you!
