### ISSUE TITLE
A small thing

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#579]
Hi Nic,

Can we get rid of this `<br />` ?
https://github.com/akeeba/fof/blob/development/fof/Form/Field/Title.php#L44
`<br />` are not very customizable, I had to recreate a Title field just to remove it. :(

**Comment by nikosdion** [comment]
We can't remove it (styling b/c break) but we can add a new attribute slug_separator with a default value of <br/>.

Nicholas K. Dionysopoulos
Director, Akeeba Ltd
https://www.AkeebaBackup.com <https://www.akeebabackup.com/>

**Comment by Eighke** [comment]
Great, thanks. :)
