### ISSUE TITLE
TreeModel->getParent()

### ISSUE THREAD

**Issue by willfaulds** [akeeba/fof#585]
TreeModel->getParent()

I believe the scope of the initial SQL query is too narrow (my terminology is probably wrong) meaning it cannot find the root node as a parent.

My test data is:
Title     lft     rgt
root      1      6
cat1     2      5
cat2     3      4

->getParent() works fine on `root` & `cat2` but on `cat1` exits shows not Items with [firstOrFail](https://github.com/akeeba/fof/blob/development/fof/Model/TreeModel.php#L1330)

[My quick workaround solution](https://github.com/willfaulds/fof/commit/99da7172a86357a54d07635e71a38ccc040a490e)

**Comment by nikosdion** [comment]
This is already covered by the tests, see https://github.com/akeeba/fof/tree/development/Tests/Model/TreeModelDataprovider.php#L921-L921 especially the "Child node, first level" case. The method works correctly as you can see in the tests..
