### ISSUE TITLE
Scaffolding questions

### ISSUE THREAD

**Issue by Eighke** [akeeba/fof#595]
Nic, 2 others questions:

- Why the "automatic" labels are using this format: COM_COMPONENT_VIEWS_FIELD_LABEL and the scaffolding that one: COM_COMPONENT_VIEWS_FIELD_LBL? LABEL and LBL for the second. Shouldn't we standardize both?

- Do we really need to define the `label=""` for the `<field>` on the browse views? Only the header will be used. And the label will be ignored anyway.

**Comment by nikosdion** [comment]
Labels: please feel free to file a PR

Empty label: No, I think that's a leftover. Feel free to PR :)

**Comment by Eighke** [comment]
#598
