### ISSUE TITLE
Undefined property: stdClass::$Null

### ISSUE THREAD

**Issue by mikeazores** [akeeba/fof#617]
I'm running todo-fof-example on my localhost machine running Joomla 3.5, PHP 5.6 and FOF 3.0.11.

When I edit an item in the backend I'm getting:

Notice: Undefined property: stdClass::$Null in /libraries/fof30/Model/DataModel.php on line 1376

**Comment by nikosdion** [comment]
This only happens if you add a known field manually without setting its Null property to "YES". The problem lies in DataModel::addKnownField which doesn't do that and of course in DataModel::check() which doesn't expect this field to be missing. Good catch!
