### ISSUE TITLE
Add More submenu items than the View Default folders

### ISSUE THREAD

**Issue by strobs** [akeeba/fof#626]
Hi PPL 

I need to have one more submenu item to link to a direct item like this 
"$link = 'index.php?option=com_compon&amp;view=Setting&amp;id=1"

How should be my toolbar.php file ?

or where can I add the submenu item to the default view.

Any help apreciated
![cap](https://cloud.githubusercontent.com/assets/2736555/17897088/c1b96eca-694a-11e6-9ad7-1c5fda2a5f3c.JPG)

**Comment by nikosdion** [comment]
Please ask your questions [on the mailing list](https://groups.google.com/forum/#!forum/frameworkonframework). The GitHub repository is for framework code issues, not discussion on _using_ the framework.
