### ISSUE TITLE
ViewTemplate vs model knownFields

### ISSUE THREAD

**Issue by pedrobicudo** [akeeba/fof#641]
I am using ViewTemplate in browse view to show relations and ratios, i.e.: users/task or task duration (today - created_on) and some others that are more complex using joins. Works fine, ViewTemplate is great, but in every line it is running a query, for small number of rows it is OK but I now have 500 items it gets slow. All information that goes through ViewTemplate is temporary and transformed, it is not the raw data that I could get with a Model field.

I'd like to insert this calculations and joins in the model, to retrieve by field name. I've read about configuring the model to identify knownFields but could not figure out how to insert data into fields that are not database columns.

Can you suggest a method to insert fields and data in the model while using F0F?

**Comment by nikosdion** [comment]
GitHub issues *is not a mailing list*.
