### ISSUE TITLE
Unable to link to buildfiles

### ISSUE THREAD

**Issue by tassosm** [akeeba/fof#658]
Running  php ../buildfiles/tools/link.php `pwd` on the main directory returns the following errors:

`Akeeba Build Tools - Linker
Internal file and directory symlinker
-------------------------------------------------------------------------------
Copyright Β©2010-2017 Akeeba Ltd
Distributed under the GNU General Public License v3 or later
-------------------------------------------------------------------------------
Symlinking folders...
PHP Notice:  Undefined offset: 1 in /var/www/akeeba/buildfiles/linklib/LinkHelper.php on line 306
PHP Stack trace:
PHP   1. {main}() /var/www/akeeba/buildfiles/tools/link.php:0
PHP   2. Akeeba\LinkLibrary\ProjectLinker->link() /var/www/akeeba/buildfiles/tools/link.php:56
PHP   3. Akeeba\LinkLibrary\LinkHelper::makeLink() /var/www/akeeba/buildfiles/linklib/ProjectLinker.php:190
PHP   4. Akeeba\LinkLibrary\LinkHelper::getRelativePath() /var/www/akeeba/buildfiles/linklib/LinkHelper.php:150
PHP Notice:  Undefined offset: 1 in /var/www/akeeba/buildfiles/linklib/LinkHelper.php on line 306
PHP Stack trace:
PHP   1. {main}() /var/www/akeeba/buildfiles/tools/link.php:0
PHP   2. Akeeba\LinkLibrary\ProjectLinker->link() /var/www/akeeba/buildfiles/tools/link.php:56
PHP   3. Akeeba\LinkLibrary\LinkHelper::makeLink() /var/www/akeeba/buildfiles/linklib/ProjectLinker.php:190
PHP   4. Akeeba\LinkLibrary\LinkHelper::getRelativePath() /var/www/akeeba/buildfiles/linklib/LinkHelper.php:150
PHP Notice:  Undefined offset: 1 in /var/www/akeeba/buildfiles/linklib/LinkHelper.php on line 306
PHP Stack trace:
PHP   1. {main}() /var/www/akeeba/buildfiles/tools/link.php:0
PHP   2. Akeeba\LinkLibrary\ProjectLinker->link() /var/www/akeeba/buildfiles/tools/link.php:56
PHP   3. Akeeba\LinkLibrary\LinkHelper::makeLink() /var/www/akeeba/buildfiles/linklib/ProjectLinker.php:190
PHP   4. Akeeba\LinkLibrary\LinkHelper::getRelativePath() /var/www/akeeba/buildfiles/linklib/LinkHelper.php:150
`

It does work on akeebasubs and strapper repos, though.

System Info:
Ubuntu 14.04.5 LTS
PHP 7.0.18-1+deb.sury.org~trusty+1

**Comment by nikosdion** [comment]
FOF no longer needs to link to anything. I simply forgot to remove templates/link.php and update the README. Hold on...
