### ISSUE TITLE
Issue after J 3.8 upgrade

### ISSUE THREAD

**Issue by go-source** [akeeba/fof#665]
My component (simple-CRM) uses FOF3 and was developed for J 3.7, PHP 7, FOF 3.1.3. A user inadvertently installed on J 3.8 PHP 7.1 and got a blank page (in a production site :/ and reinstalled with Akeeba). I tested and confirmed. His screen shots say on backend “Call to undefined method FOF30\Platform\Joomla\Platform::getSessionVar()” and the button to return to control panel, while on his URL front end: 0 Class ‘FOF30\Date\Date’ not found. 
I could not reproduce the same message, right on install my test site says "Content Encoding Error / The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression./Please contact the website owners to inform them of this problem."

Before I spend long hours debugging I'd like to know if someone has faced this issue before.
Thanks,

**Comment by go-source** [comment]
Sorry for the inconvenience. After turning of GZIP compression I could get back my test server. It happens that uninstalling Akeeba Admin resolved. I will post the issue there. Messages are:

Warning: include_once(/home...go-source.com/libraries/fof30/Date/Date.php): failed to open stream: No such file or directory in /home/...go-source.com/plugins/system/admintools/admintools.php on line 88

Warning: include_once(): Failed opening '/home...go-source.com/libraries/fof30/Date/Date.php' for inclusion (include_path='.:/opt/alt/php56/usr/share/pear:/opt/alt/php56/usr/share/php') in /home...go-source.com/plugins/system/admintools/admintools.php on line 88

**Comment by nikosdion** [comment]
Some of your FOF files are out of date. Install it again twice in a row without uninstalling and make sure you clear any code caches on the server.

**Comment by go-source** [comment]
Just did. Thanks. Also fixed Akeeba Admin (obvious).
