### ISSUE TITLE
CSV format: Exception thrown with no records

### ISSUE THREAD

**Issue by tampe125** [akeeba/fof#666]
If we try to export an empty dataset, we get an `AccessForbidden` exception.  
Looking at the code, this is the source of the issue: [Csv.php#L156](https://github.com/akeeba/fof/blob/development/fof/View/DataView/Csv.php#L156)  
Why there's such such there? Isn't an empty set an allowed one?

**Comment by nikosdion** [comment]
Not a bug, really ;) This is the correct behaviour. You cannot export an empty set. The result would be a 0-byte file which is an invalid CSV (you need to have at least one data row).
