### ISSUE TITLE
RFC on PR proposal concerning relationTypes

### ISSUE THREAD

**Issue by calligraphic** [akeeba/fof#675]
I'd like to be able to add custom relation types, in addition to the standard `hasMany`, etc. My use case is to add relation types that implement table inheritance (e.g. use a discriminator field). If this addition would be well-received, I'll send a PR for it but wanted to check and see if there were any suggestions. 

Implementation might be adding an `addRelationTypes` method to the `RelationManager` class. It would only work with relations added via direct calls to `addRelations`, and wouldn't work with relations added as configuration options to the model constructor. I don't see an easy way to do it otherwise since the `relationTypes` var is static in `RelationManager`.

**Comment by nikosdion** [comment]
I understand what you want to do and it will be rather complicated. You're a brave man :) If you are going to write the code, by all means, please do submit a PR. Please remember to add Unit Tests for this since it's a non-trivial functionality with possibly deeper effects in FOF.

**Comment by calligraphic** [comment]
I think my initial thought on adding an `addRelationTypes` method to the relation manager will be unnecessarily brittle since the call order matters with `addRelations`. It would also require FS touches for each call to verify the existence of added relation types, in order to be consistent with `getRelationTypes` exception handling.

I think it might be better to modify the `RelationManager` class `getRelationTypes` static method to allow adding additional relation types. My thought would be to allow components to add additional relation types by putting them in a `administrator/com_componentname/Relation` (singular) directory. Some questions:

1. Should this be an opt-in behavior, with a configuration option to enable it in `<model>` in the fof.xml `<common>` or `<backend>` config file?
2. Is standardizing on custom relations needing to be in a `Relation` directory in the admin part of the site okay, or should developers have more flexibility to specify the directory in the configuration?

**Comment by nikosdion** [comment]
We can definitely do it an opt-in behaviour under the `<model>` key. This means that it can also be set up by overriding the constructor, just like we do with behaviors.

If it's opt-in, we can provide a qualified class names in the custom relation types setup. For example:
```xml
<model>
  <relationType name="myType" class="\Akeeba\Example\Admin\Relation\MyAdvancedRelationType" />
  <relationType name="myOtherType" class="\Akeeba\Example\Site\Relation\SomeOtherType" />
</model>
```

Doing it that way would make the point in your second question optional. We could have relation types in the Relation directory as a best practice but not as a mandatory requirement. The fully qualified class type makes sure the autoloader can find the class no matter what.

The only thing you have to be careful about is that you need to set up relation types before you set up the relations themselves.

**Comment by calligraphic** [comment]
Thanks for the feedback, that seems like the right approach. I'm still a couple of weeks from needing this functionality in my project so I haven't started on the PR, but I've been thinking about it. I understand the static is to allow magic discovery of the `Relation` types, but the default types (`BelongsTo`, `BelongsToMany`, `HasOne`, and `HasMany`) seem stable and integral to the framework. Would you object to my PR factoring out the static in `RelationManager` and using instead a list of default framework `Relation`s?

 A PR adding documentation to `RelationManager` about steps to take in order to add a new default framework relation type might be adequate. Using a list and factoring out the static I think would give a more consistent API for adding new relation types, similar to `addBehaviour` and `addRelation` (e.g. can be set in any of `fof.xml`, the `DataModel` `$config` array, or with a call to an `addRelationTypes()` method) with the requirement that the relation type has to be added before actual relations.

Also, one thing I noticed is that I believe the `RelationManager`s `getRelationTypes()` function has the only directory-scan in a hot path of the framework. `DataModel`'s `addBehaviour()` for example will be opcached in PHP 7.x, but relation types never will be.

**Comment by nikosdion** [comment]
Closing due to long period of inactivity.

**Comment by calligraphic** [comment]
I had an extended hospitalization last autumn for some health issues, sorry to leave this open so long. I'll submit a PR.

**Comment by nikosdion** [comment]
I am sorry to hear that.

Please make the PR against the fof4 branch. The development branch currently contains FOF 3.x which has entered maintenance mode.
