### ISSUE TITLE
The future of FOF and Joomla 4

### ISSUE THREAD

**Issue by mblackritter** [akeeba/fof#676]
I'm seriously considering FOF for a new extension/component which requires to be integrated into Joomla. I was surprised that Joomla, in all these years, didn't evolve much in the areas of basic modern architectures (ORM, etc., to say the least). So to me, it seems like "FOF to the win", but was surprised of the (seemingly) lack of support from the Joomla community, aside that it was even officially a part of the Joomla core for quite some time.

So for me it would be interesting to know how well FOF will likely play in terms of Joomla 4. I'm currently not already deep enough into FOF to get the whole picture and answer it myself, how deeply FOF integrates into parts which change with Joomla 4, so please excuse my "sincere n00bness". 😊

Btw., while reading your (@nikosdion) last blog post concerning Joomla's future architecture and the comments there ([Joomla! 4 and Beyond: architecture and design](https://www.dionysopoulos.me/joomla-4-and-beyond-architecture-and-design/)), I'd the impression that the ideas which FOF follows seem not to get much love on the side of Joomla developers. Much to my surprise, I've to say, because what you outlined there (Already in 2015!), incl. your responses to the comments, seems to would've caught up on what's common nowadays (2018).

**Comment by mblackritter** [comment]
Wow, thanks for the extensive and ensuring response!

I don't mind possible required changes (small or big) when Joomla 4 hits final, it was purely about the outlook for FOF, for which I'm surely satisfied now.

When I said ORM, I just used the term for better database abstraction/handling and generic example of lack of modern concepts in current Joomla. As I read your article thoroughly, I wasn't referring to a full blown "real ORM", so excuse that you'd to waste some time covering this topic (again).

So it all comes along nicely with Joomla and FOF, which was my concern, because it wasn't obvious for bystanders like me and I'm sure this post will help others with the same idea, to build modern Joomla extensions, where "being-ORM-like" is of course just a part of my reasons for FOF.

Thanks again and cheers on FOF! 🤩

**Comment by nikosdion** [comment]
You're welcome :)
