### ISSUE TITLE
Warning: "continue" targeting switch is equivalent to "break".

### ISSUE THREAD

**Issue by neoacevedo** [akeeba/fof#679]
In PHP 7.3, _**continue**_ inside a switch generates a warning:

> Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

This is present in https://github.com/akeeba/fof/blob/development/fof/TransparentAuthentication/TransparentAuthentication.php#L324 into the `switch($method)` code for each empty conditional.

I think you could create a validator for PHP version like:
```php
switch ($method) {
    case 'HTTPBasicAuth_TOTP':
        if (empty($this->fofAuth_Key)) {
            if (version_compare(phpversion(), '7.3.0', '>=')) {
                continue 2;
            } else {
                continue;
            }
        }
...
}
```

**Comment by nikosdion** [comment]
Um, I already fixed that last week?

**Comment by nikosdion** [comment]
So, I _had_ fixed it... but only in the FOF 4 work-in-progress branch. Oops. I backported the fix to FOF 3.

FYI, the `continue 2` construct is valid for all versions of PHP supported by FOF 3 (PHP 5.4 to 7.3 inclusive). There is no need to have a conditional.
