### ISSUE TITLE
Error after update FOF 3.1.3 to 3.3.9

### ISSUE THREAD

**Issue by go-source** [akeeba/fof#680]
My component was developed using FOF 3.1.3. Updating any Akeeba component updates FOF and my component views in the backend show the error below. Reverting FOF to 3.1.3 fixes my component but breaks Akeeba views (obvious). Frondend is OK. Do you have any guidelines that I could follow to upgrade my component?  I do not know where to start and I have limited time to dedicate to this free open source component.
---
An error has occurred.
    0 Call to a member function getModel() on null 
Call stack
---
# | Function | Location
1 | () | JROOT/libraries/fof30/Form/Field/Numeric.php:30
2 | FOF30\Form\Field\Numeric->__construct() | JROOT/libraries/fof30/Form/Form.php:650
3 | FOF30\Form\Form->loadType() | JROOT/libraries/fof30/Form/Form.php:589
4 | FOF30\Form\Form->loadFieldType() | JROOT/libraries/fof30/Form/Form.php:932
5 | FOF30\Form\Form->loadField() | JROOT/libraries/joomla/form/form.php:358
6 | JForm->getFieldset() | JROOT/libraries/fof30/Render/AkeebaStrapper.php:819
7 | FOF30\Render\AkeebaStrapper->renderFormBrowse() | JROOT/libraries/fof30/Render/AkeebaStrapper.php:1452
8 | FOF30\Render\AkeebaStrapper->renderForm() | JROOT/libraries/fof30/View/DataView/Form.php:108
9 | FOF30\View\DataView\Form->getRenderedForm() | JROOT/libraries/fof30/View/DataView/Form.php:65
10 | FOF30\View\DataView\Form->display() | JROOT/libraries/fof30/Controller/Controller.php:546
11 | FOF30\Controller\Controller->display() | JROOT/libraries/fof30/Controller/DataController.php:432
12 | FOF30\Controller\DataController->browse() | JROOT/libraries/fof30/Controller/Controller.php:410
13 | FOF30\Controller\Controller->execute() | JROOT/libraries/fof30/Controller/DataController.php:158
14 | FOF30\Controller\DataController->execute() | JROOT/libraries/fof30/Dispatcher/Dispatcher.php:175
15 | FOF30\Dispatcher\Dispatcher->dispatch() | JROOT/administrator/components/com_gscrm/gscrm.php:17
16 | require_once() | JROOT/libraries/cms/component/helper.php:389
17 | JComponentHelper::executeComponent() | JROOT/libraries/cms/component/helper.php:364
18 | JComponentHelper::renderComponent() | JROOT/libraries/cms/application/administrator.php:98
19 | JApplicationAdministrator->dispatch() | JROOT/libraries/cms/application/administrator.php:156
20 | JApplicationAdministrator->doExecute() | JROOT/libraries/cms/application/cms.php:265
21 | JApplicationCms->execute() | JROOT/administrator/index.php:51

**Comment by nikosdion** [comment]
Change all fields of type=“numeric” to type=“number”. This is documented in the changelog and the wiki. It’s a change required for working with PHP 7.2 and later. 

Nicholas K. Dionysopoulos Director


Akeeba Ltd • 51 Metochiou Str. • Flat 303 • 1101 Nicosia • Cyprus 

Web administrator and security tools you can trust.

**Comment by go-source** [comment]
Thank you.
I had read the Numeric to Number issue. However, I changed only one view to test and it did not work, then I asked the question. Now, after replacing all places and views, it works fine.
