### ISSUE TITLE
View engine order for extending the viewEngineMap

### ISSUE THREAD

**Issue by venomdev** [akeeba/fof#694]
I'm working with v3.7 and I plan to add some Twig template support because my designer and users are more familiar with Twig. The problem I came across was if I add the View options to support default.twig.php it's still using the PhpEngine because the viewEngineMap order is 

1. .blade.php
2. .php 
3. .twig.php

My extension is detected after .php which means it never runs the Twig engine.

If the order was changed so that new viewEngineMaps were listed before the built in types then .php would be the last failsafe and not pick it up before the other engine maps.

You can see the order in FOF30\View\View.php getEngine()

```
var_dump($this->viewEngineMap);

/app/libraries/fof30/View/View.php:1251:
array (size=3)
  '.blade.php' => string 'FOF30\View\Engine\BladeEngine' (length=29)
  '.php' => string 'FOF30\View\Engine\PhpEngine' (length=27)
  '.twig.php' => string 'VenomDev\FOF3Test\Admin\View\Engine\TwigEngine' (length=46)
```

the line to change is 249

`$this->viewEngineMap = array_merge($this->viewEngineMap, $config['viewEngineMap']);`

to 

`$this->viewEngineMap = array_merge($config['viewEngineMap'], $this->viewEngineMap);`

**Comment by venomdev** [comment]
Rethought the fix, it should probably be

`$this->viewEngineMap = array_merge($config['viewEngineMap'], $this->viewEngineMap, $config['viewEngineMap']);`

This will preserve the order and any over rides.

**Comment by nikosdion** [comment]
I did it a bit differently to make sure that only the `.php` fallback cannot be overridden and is always at the end, fulfilling its role as a fallback. With your change you would never be able to reassign `.blade.php` to a different engine which could be an issue and there's no reason for us to prevent.

To be clear, the intention has always been that you can add new template engines or override existing ones _except_ the plain `.php` fallback which should always be the last thing FOF would try to use. The implementation didn't follow the intention as you correctly identified. This change should do the trick.

**Comment by venomdev** [comment]
Cheers, looks like it should do the trick perfectly.
