### ISSUE TITLE
FOF 3.0

### ISSUE THREAD

**Issue by Skullbock** [akeeba/fof#701]
Hi @nikosdion sorry to bother you.
I have an issue with the latest akeeba updates: When i install the latest akeeba backup, it seems to delete the `libraries/fof30/includes.php` and therefore breaks any custom component based on FOF30 installed on the site.

Is this something intentional?
Thanks

**Comment by nikosdion** [comment]
FOF 3 will only be uninstalled if there are no other extensions depending on it.

If your extensions are correctly marked as dependent you will not have this problem.

**Comment by Skullbock** [comment]
I'm sorry, i think i am at a loss here.
How do i mark my extension built with FOF3 as dependent on FOF3? 

Can i suggest to avoid uninstalling it and just show a warning message, much like Peter did with his old NoNumberFramework?

**Comment by nikosdion** [comment]
It's been documented in https://github.com/akeeba/fof/wiki/The-InstallScript-class since June 20th 2015. 

And no, you not following the documentation is not a valid reason for me to make my extensions leave things behind on uninstallation. That's the whole point of dependency tracking.

Issues like that or Miguel getting annoyed I didn't want to reinvent Joomla's form package is why FOF 4 is essentially a private framework without any public documentation.

**Comment by Skullbock** [comment]
Hi Nick, i didn't mean for it to be an insult or anything. Being a past FOF contributor and big fan, i just wanted to share an idea.
My issue is that some of my exts where a porting from FOF2, and therefore didn't have the "install script" class. They are custom made for a single client, and that class never gets used.

Is there a way for me to do this "ex-post", on existing installations? Is this information (the dep tracking) stored somewhere or is it resolved realtime by checking each installed ext for a script class that extends FOF installer?

Thanks again

**Comment by nikosdion** [comment]
It's all stored in a common table. Check the code of the installer class and how Akeeba Subscriptions works per the links in the page I linked.

I will prevent FOF 3 from being uninstalled on upgrade of our extensions for the time being.

**Comment by Skullbock** [comment]
That's great news, will update the table in the meantime.
Thanks again!
