### ISSUE TITLE
Autoloader - ComponentVersion alias path

### ISSUE THREAD

**Issue by anibalsanchez** [akeeba/fof#702]
Hi,

I'm migrating a couple of extensions and I've noticed that the Autoloader ComponentVersion alias path points to the same file:

```php
		'FOF40\Utils\ComponentVersion'            => 'FOF40\Utils\ComponentVersion',
```

And, it should go to `FOF40\JoomlaAbstraction\ComponentVersion`.

Thanks in advance.

**Comment by nikosdion** [comment]
Can you please make a PR?
