### ISSUE TITLE
Message !FOF40_INCLUDED ... You need to have (FOF) 3

### ISSUE THREAD

**Issue by anibalsanchez** [akeeba/fof#703]
This is not an issue on FOF, just a tweak in the warning messages on Akeeba and AdminTools.

```php
	if (!defined('FOF40_INCLUDED') && !@include_once(JPATH_LIBRARIES . '/fof40/include.php'))
	{
		(include_once __DIR__ . '/tmpl/CommonTemplates/fof.php') || die('You need to have the Akeeba Framework-on-Framework (FOF) 3 package installed on your site to use this component. Please visit https://www.akeeba.com/download/fof3.html to download it and install it on your site.');

		return;
	}
```

**Comment by nikosdion** [comment]
FOF 3 is end of life. FOF 4 is deprecated and will become End of Life in August 2023. Please read https://www.akeeba.com/news/1745-about-our-fof-and-fef-frameworks-and-their-future.html

Akeeba Backup 8 and Admin Tools 6 are now in maintenance mode. Akeeba Backup 9 and Admin Tools 7, the current and Joomla–4–only versions, do not use FOF. Please read https://www.akeeba.com/news/1747-joomla-4-is-around-the-corner.html
